services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5000:5000"  # Expose on localhost
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - worker_experimentation_network

  flask-app:
    build: .
    expose:
      - "5000"
    deploy:
      replicas: 2
      #endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
    networks:
      - worker_experimentation_network
    volumes:
      - ./requirements.txt:/app/requirements.txt
    command: >
      gunicorn --worker-class gevent --bind 0.0.0.0:5000 --workers 1 --worker-connection 1000 app:app

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
    networks:
      - worker_experimentation_network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  mysql-data:

networks:
  worker_experimentation_network:

