services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    container_name: flask-app
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: "1.0"         # Limit to 1 CPUs
          memory: "2G"       # Limit to 2 GiB of memory
    volumes:
      - ./requirements.txt:/app/requirements.txt
    command: >
      gunicorn --worker-class gevent --bind 0.0.0.0:5000 --workers 1 --worker-connection 1000 app:app

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: strong_password     
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/my.cnf 

volumes:
  mysql-data:
